[SQUASH] vendor: roomservice delivers you lunch combos from the github
fix roomservice formatting

support product names with _ in them

fix roomservice to handle pagination

Change-Id: I4923c2f768094dbad8e06a72d9f27d46414030ab

-----

roomservice: Add lightweight dependencies to repositories

Roomservice can already fetch your slim_<device> without the need for a
manifest entry.

However, when working with common repositories, there is no way of
actually fetching them without adding to the manifest. This patch
introduces a lightweight dependency system. Each repository can have a
slim.dependencies in the following json format:

[
  {
    "repository": "repository_name_on_cm_organization"
    "target_path": "target/path"
  },
  ...
]

For instance, for cm_anzu I need android_device_semc_msm7x30-common and
android_device_semc_mogami-common. I would add both to slim.dependencies
as follows:

[
  {
    "repository": "android_device_semc_msm7x30-common",
    "target_path": "device/semc/msm7x30-common"
  },
  {
    "repository": "android_device_semc_mogami-common",
    "target_path": "device/semc/mogami-common"
  }
]

Roomservice would then fetch the anzu repository, parse the dependency
files and add/fetch/sync these additional repositories if they don't
exist already.

This also adds pretty printing to the output xml.

Change-Id: I9cc847adfc717a06439bc6094213ed6492343158

roomservice: Add branch support to slim.dependencies

Allow the slim.dependencies entries to provide an optional "branch" for
the repository dependencies. Added to fully support
http://wiki.cyanogenmod.com/wiki/Integrated_kernel_building

Change-Id: I35b51920d296afa329411af6172c7bd9aeef4af8

roomservice: Fill in dependencies for already-deployed repositories

Change-Id: I01fd408c9c4bfa78097c7f848b2556d2b2b180f3

roomservice: Extend dependency-checks to devices in main manifest

CM currently keeps devices inherited from AOSP in the main manifest,
so take that into account as well when checking device paths

Change-Id: I9663f283617f237428b4eaa0cd60b5de2b86a7b9

make compatible with github v3 api

Change-Id: Iff6f1f9099cdc5d2b49e04000b5fe3d04aa5d7e4

Fixed build for full-eng

Previously
Traceback (most recent call last):
  File "build/tools/roomservice.py", line 153, in <module>
    repo_path = get_from_manifest(device)
NameError: name 'device' is not defined

** Don't have a product spec for: 'full'
** Do you have the right repo manifest?

Now
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=4.0.4
TARGET_PRODUCT=full
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a
HOST_ARCH=x86
HOST_OS=linux
HOST_BUILD_TYPE=release
BUILD_ID=IMM76L
============================================

Change-Id: Ib513705aba9a7a52a971ab64102ecbe9fddfb97a

roomservice: Bump github request per_page to 100

Change the number of repos per page from the default 30
to 100.

We seem to be hitting the rate limit on the jenkins server.

Change-Id: Ie733feaa0414cbfebb7efcfc1e24d94e1e466d1b

roomservice: Add support for netrc

Change-Id: I1f5e11e40125abd0c4e4c8d8294d4fc09bfdc30a

roomservice: Handle missing netrc file

Change-Id: If981fe79dc3e2191434301239b0cd585be8b4730

roomservice.py: Verbose error when a branch is missing.
Also add ROOMSERVICE_BRANCHES environment variable to use fallback branches.

Change-Id: I3c2b1d79fc185c1f1e1d658e5ca4f78e688780e2

roomservice.py: Fixups around fallback branches not being used by dependencies when ROOMSERVICE_BRANCHES is defined.

Change-Id: Ifb42a023cae5f62ac8f9cf7832125b91b431169c

roomservice: Allow following up tag references

This is now needed for release builds

Change-Id: I8c5f87341059b3b15ee853312b71df73790ad0d8

build: local_manifest.xml deprecated, use local_manifests

Patch Set 2:- Use roomservice.xml instead of slim.xml.

Change-Id: I3d8a6ef3907b92808662cbba912cea5ed38d0bde

Fix fallback branch search in roomservice

If you provided a fallback branch to roomservice via the
ROOMSERVICE_BRANCHES environment var the branch search would fail
if the device repo had any tags.

Fixed this by appending the tag search results to the branch
search results instead of overwriting them

Change-Id: I73a11af1500bd04e346f08ec3f83454502f3a169

roomservice: Fix wrong assumption about path of active manifest

Change-Id: Id740ff4b848e6ccbfd658be4846197b8ca519237

roomservice: When validating the presence of a repo, check main manifest too

Change-Id: If680536484074b473458723d93e783d074d7f669

roomservice: Bump devices per page to 200

Limit was reached again when attempting to
lunch various projects, such as steelhead.

Change-Id: I2f3b9705e07e1e47b86857aeb383cf7c99fcdbdc
Signed-off-by: William Roberts <bill.c.roberts@gmail.com>

roomservice: Fix assumptions about the branch naming

We can't just split from the last slash anymore, since we're using
those to distinguish the stabilization branches

Change-Id: Ia175dd317f508e99b275b56e9c83bd4729a75ddb

roomservice: Add recursive dependencies

Dependency repositories can now have dependencies themselves

Change-Id: I33a28709170da52bc98f4a62387927e3a11b2450
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: python3 support

Change-Id: I7621818ba7ed997676728fe865f37a25b3a5b8b5
Signed-off-by: Chirayu Desai <cdesai@cyanogenmod.org>
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: Improve new device retrieval

Without credentials, GitHub's search API limits requests to 60/hr.
The existing method to add a new device is to fetch JSON-formatted info
for ALL CM repositories and then search for the device. In doing so,
more than 10 pages of results are returned (i.e. more than 10 requests
per device). This is clumsy, slow, and limits use of roomservice to
only ~5 devices per hour.

Instead, only return search results for repositories that have the
device name in the repository name. Then, one device = one request.
It's faster and allows closer to 60 device setups / hr.

Additional bailouts are included to stop the script earlier than later
if a device is not found.

Change-Id: I7f914d7ede82da0f100d9fd6cf8b603177962e48
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: Fix search of devices forked.

Commit "roomservice: Improve new device retrieval" introduced a
regression where repositories that were forked to PixelExperience were omitted from
search results. This fixes that issue.

Change-Id: I7bf54129b5da1749abe5b2b9a492cb93e6ee41a6
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: Improve error handling on search

Use the relevant forms of 'except' for urllib and parsing instead of a
general except which was performed too late anyways.

Change-Id: Ia1fc89dd5a8a703fc0175aef7b6dd013a44a2c8e
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

vendor: Fixup roomservice

Change-Id: Ibc77861c068edefc35d6925d21f320c187bacd0b
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: hack the calculated revision in to shape

Change-Id: Ibccc93a6d899e7c7f2dad2f493a3ca1fc0a2815a
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

Overhaul roomservice for sanity and cleanliness

I wish anyone porting this over to other versions of roomservice luck

Change-Id: I372d254469f5b3306e0a5e370d26d22ed6e49eaa
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: check against the path, not name

For a while now, it's projects have been allowed to fetch from
the same location. The only reliable way to check is with the
target path, so we use this now.

Change-Id: Ia88bd3a5a56d5de2110f1c0d3ce332060732f716
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: add branch to deps if not provided

this matches the behaviour (more or less) as if they were
added in normal mode

Change-Id: I1fcef29c8c34d2f74eb8e184a272610e02220ad8
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: touchup revision assignment

don't assign the revision if the calculated one is the
same as the default one.

fallback to the custom_default_revision if can't calculate
a revision in deps only mode

Change-Id: I5f180ecf766b95eb41a716234d4e42d7d4e4a942
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: Update roomservice fallback branch

Change-Id: I284e6370f19ab979569bfc70ddc1dd850640d339
Signed-off-by: Josue Rivera <prbassplayer@gmail.com>
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: use force-sync when adding projects with roomservice

This works around the error
GitError: --force-sync not enabled; cannot overwrite a local work tree
when using roomservice.

Since this should only trigger when the device repos haven't been
checked out yet, we can use force-sync to overwrite any roomservice
device paths in the .repo directory.

Change-Id: Iac54a8a2f2913f82f8ca6497b8785a9d5769640b
Ticket: CYNGNOS-735
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: Bringup for ThePixelProject

Change-Id: Id6f1f8fbf37e5539fc75abeeac1f8552ba9322b5
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: rewrite some logic

  * Never experimented about properly with old.
  * If repo_name didn't have a '/', and remote wasn't devices, everything would
    break.
  * Now if remote isn't specified, add it dynamically based on 2 conditions.
  * If the repo_name has a '/', default to "github" remote.
  * If it dosen't have a '/', default to our devices organization.
  * Also add in support for setting a custom clone-depth for any dependency.
  * Useful for stuff like prebuilt kernels from AOSP.

Change-Id: Iebda1645cfbf6ad51f4670a7d5e49d553b5a0e2d
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: give us some more info about what we're about to sync

  * repo_target -> repo_path

Change-Id: Ib974593a596e6a4fd724b8516b279c73110ad6d2
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: fix a weird error

  * Only way I could replicate it was if I delete local manifest after having my trees synced and try to lunch
  * Unofficial builders seemed to be facing it quite a bit
  * The default manifest will never have device trees, only local manifest will

Traceback (most recent call last):
  File "build/tools/roomservice.py", line 365, in <module>
    main()
  File "build/tools/roomservice.py", line 307, in main
    repo_path = get_from_manifest(device)
  File "build/tools/roomservice.py", line 144, in get_from_manifest
    lp = local_path.get("path").strip('/')
AttributeError: 'NoneType' object has no attribute 'strip'

** Don't have a product spec for: 'aosip_bacon'
** Do you have the right repo manifest?

Change-Id: Iabc41d344320b3bec96d2c3c4e5b11878811a04f
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: tell user in the case of a dependency already in manifest

Change-Id: I4177a4d36775dc22c6430c5bff1878967e1f5856
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: Change 'bailing out' message to something more friendly

Change-Id: Iee519ea5cbfa92b6bb26e33d2bac3d2335c770a8

-----

tools: Fix spelling in roomservice

`Trying dependencies-only mode on anon-existing device tree?`
is wrong and annoying.

Change-Id: I269fdf47234bb83d18c1ddf4e344dd6b9b70b736
Signed-off-by: Harsh Shandilya <harsh@prjkt.io>

-----

roomservice: just check the local manifest

  * We don't have any trees in the main manifest
  * This breaks angler (and more), because AOSP default.xml has them
    (Dosen't affect sync because we remove it with <remove-project />)

Change-Id: Idcc2c5d9b8fab91ea29f003a264949affbacae1f
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

-----

roomservice: use python3

  * Cleanup a bit, remove useless code
  * Fixup indentation, py3 hates a mix of tabs and spaces
  * Account for cases where the name of the repository is not set
    (Don't try to add the repo in such a case)
  * If the path isn't set, take the last part of the name as the path

[akhil: add back AOSiP copyright]
Change-Id: I7f43e425b13ec04ea1ff938df18c597170945bf7
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>
(cherry picked from commit 7565c60aef85d1ced2df3ff849db9c6b847ff02c)

-----

roomservice: Allow using access token for github API

 * to fetch private repos using github API
 * store credentials in .netrc in the format:

login api.github.com
username <username>
password <token>

Change-Id: I9e75146ca6f8bd728026187a7fa7f8f18d4e549c

-----

roomservice: Speed up the dependencies repo sync

-----

roomservice: Support new manifest formats

.repo/manifest.xml is no longer a symlink becuase apparently windows
developers need to use repo and windows needs admin for symlinks.

https: //gerrit.googlesource.com/git-repo/+/a269b1cb9dc21dfd598bfea3766206b606ad4589
Change-Id: I88ea0295133959136d7214f13a76b66d89dc88d4

-----

roomservice: Allow replacing already existing projects

Signed-off-by: Adithya R <gh0strider.2k18.reborn@gmail.com>

-----

roomservice: Adapt for new python versions

- 3.9 deprecated .getchildren so this just works

-----

roomservice: Reverse existing project checking order

 * check in wave and lineage manifests, then check in aosp, this allows
   to replace repos that are already tracked in wave (for eg, from a
   different branch)

Co-authored-by: Diogo Ferreira <defer@cyanogenmod.com>
Co-authored-by: Chirayu Desai <cdesai@cyanogenmod.org>
Co-authored-by: Matt Mower <mowerm@gmail.com>
Co-authored-by: Nicholas Flintham <nick@flinny.org>
Co-authored-by: Josue Rivera <prbassplayer@gmail.com>
Co-authored-by: Akhil Narang <akhilnarang.1999@gmail.com>
Co-authored-by: LuK1337 <priv.luk@gmail.com>
Co-authored-by: Adithya R <gh0strider.2k18.reborn@gmail.com>
Co-authored-by: Tom Powell <tom@powell.io>
Co-authored-by: ender1324 <ender1324@abv.bg>
Change-Id: I2a094bd1ab6f11ea912f4daba147dba8f6c083a9